services:
  - type: web
    name: meditation-exercise-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    gunicorn app:app --workers 1 --threads 1 --timeout 60

